"""
Django settings for noah project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from pathlib import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(os.path.join(__file__, os.pardir))))
BASE_DIR = Path(BASE_DIR)
CURR_DIR = os.path.basename(os.path.dirname(__file__))
CONF_DUMP_DIR = "/data/xl/Dags-Dashbord/dags_conf"
CONF_TMP_DUMP_DIR = "./work_dir/tmp"
ONLINE_PACKAGE_DIR = "./work_dir/online_pkgs"
WORK_PACKAGE_DIR = "/data/xl/Dags-Dashbord/package_files"
PACKAGE_PATH = "/data/xl/Dags-Dashbord/package_files"

ZK_HOSTS = "127.0.0.1:2181"
ZK_CLUSTER_DIR = "/dags/clusters"
ZK_DAGS_DIR = "/dags/dags"
NODE_PORT = 18792

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ib3j-d5eu)h7judfpt5_%9hrwanho=*6$pcye#4w6h$av@eeg4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
SITE_URL = 'http://127.0.0.1:8000/'
ALLOWED_HOSTS = ['*']
PROJECT_NAME = "noah"
SITE_ADMIN = ""
# Application definition
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_vite',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'noah.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'zjchain/templates'),
            BASE_DIR / 'web',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'noah.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     },
#     'clickhouse': {
#         'ENGINE': 'clickhouse_backend.backend',
#         'NAME': 'default',
#         'HOST': '10.101.20.11',
#         'USER': 'default',
#         'PASSWORD': '',
#         'TEST': {
#             'fake_transaction': True
#         }
#     }
# }
#
# DATABASE_ROUTERS = ['noah.settings.dbrouters.ClickHouseRouter']
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MY_APPS = (
    'zjchain',
)

INSTALLED_APPS += MY_APPS

TEMPLATE_DIRS = [
    os.path.join(BASE_DIR, 'zjchain/templates'),
]

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
DJANGO_VITE_DEV_MODE = False
STATIC_URL = '/static/'
STATIC_ROOT = Path(BASE_DIR) / 'collectedstatic'
DJANGO_VITE_ASSETS_PATH = os.path.join(os.path.join(BASE_DIR, 'static'), "dist")
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),
                    DJANGO_VITE_ASSETS_PATH]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r".*",
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
X_FRAME_OPTIONS = 'ALLOWALL'
XS_SHARING_ALLOWED_METHODS = ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
