# Generated by Django 2.1.4 on 2021-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_task_id', models.IntegerField(default=0)),
                ('next_task_id', models.IntegerField(default=0)),
                ('stream_type', models.IntegerField(default=0)),
                ('file_name', models.CharField(default='', max_length=1024, null=True)),
                ('rcm_context', models.CharField(default='', max_length=256, null=True)),
                ('rcm_topic', models.CharField(default='', max_length=256, null=True)),
                ('rcm_partition', models.IntegerField(default=0)),
            ],
        ),
    ]
