# Generated by Django 2.1.4 on 2021-10-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0002_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='dispatch_tag',
            field=models.IntegerField(default=-1),
        ),
    ]
