# Generated by Django 2.1.4 on 2021-10-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0003_edge_dispatch_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('prev_task_id', 'next_task_id')},
        ),
    ]
