# Generated by Django 2.1.4 on 2021-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0004_auto_20211019_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='pipeline_id',
            field=models.IntegerField(default=0),
        ),
    ]
