# Generated by Django 2.1.4 on 2021-10-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0005_edge_pipeline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_update_time_us',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
