# Generated by Django 2.1.4 on 2021-10-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0006_task_last_update_time_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_update_time_us',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
