# Generated by Django 2.1.4 on 2021-10-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0007_auto_20211029_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='last_update_time_us',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
